---

- name: Build docker images
  docker_image:
    build:
      path: "{{ exporter_root_path }}/Dockerfiles"
      pull: false
      dockerfile: "{{ item }}"
    name: "{{ item }}"
    tag: latest
    source: build
  become: yes
  tags: molecule-notest
  with_items:
    - snmp_exporter
    - blackbox_exporter
    - ping_exporter
